### PR TITLE
Data cleanup

### PR DESCRIPTION
**Pull request by rhit-hurtigna**
This removes some deprecated fields from the lesson progression system, logging of the RESOLVE verifier's responses in the datalog table, and also implements more robust error handling when the verifier finds a syntax error.

I'm logging info about each VC as well as the time it took for the verifier to respond, here's an example of the VC data that'd be logged:

~~~(.json)
[
  {
    "vcGivens": "",
    "sourceFile": "BeginToReason.fa",
    "vcGoal": "((E' + 1) = (E' + 2))",
    "lineNum": "12",
    "vc": "0_1",
    "vcInfo": "Explicit Confirm Statement: BeginToReason.fa(12)",
    "result": "Timeout after 7000 ms"
  },
  {
    "vcGivens": "",
    "sourceFile": "BeginToReason.fa",
    "vcGoal": "true",
    "lineNum": "4",
    "vc": "0_2",
    "vcInfo": "Ensures Clause of Main: BeginToReason.fa(4)",
    "result": "Proved, 0 ms"
  }
]
~~~

In the case that the verifier throws an error, it will be stored similarly (the nesting seems redundant, but it's the same formatting as what RESOLVE sends so I figured I'd keep it for interoperability's sake:
~~~(.json)
[
  {
    "errors": [
      {
        "error": {
          "fn": "BeginToReason.fa",
          "ln": "15",
          "msg": "No such symbol: syntaxerror        Confirm X = syntaxerror;                    ^"
        }
      }
    ]
  }
]
~~~

Let me know if there are any changes you'd like to see in how these are stored.

### CODE REVIEW

**Review by yushan87 — COMMENTED** [review]
Are we storing these as JSON objects in our DB or did you convert these?

**Comment by rhit-hurtigna** [comment]
> Are we storing these as JSON objects in our DB or did you convert these?

They're being stored as text fields directly formatted in JSON

**Review by yushan87 — COMMENTED** [review]
It is possible that at some point we also "clean up" the result coming back from the VC generator (WebIDE) in the future. Will it break the database table if we do?

**Comment by rhit-hurtigna** [comment]
> It is possible that at some point we also "clean up" the result coming back from the VC generator (WebIDE) in the future. Will it break the database table if we do?

Depending on the extent of the changes, it definitely could - however, that problem will be present regardless of these extra logs since we already make assumptions about the protocol when determining whether verification was successful or not.

**Review by yushan87 — APPROVED** [review]
If this changes the SQL lite database, please send me a new version on Slack.

**Pull request merged**
